function [fitresult, gof] = createFit(x, y, c)
%CREATEFIT(X,Y,C)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Input : y
%      Z Output: c
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Aug-2015 15:45:19


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( x, y, c );

% Set up fittype and options.
ft = fittype( 'a1*( exp( -0.5 * (X - x01).^2./sx1.^2 - 0.5 * (Y - y01).^2./sy1.^2 ) ) +  a2*( exp( -0.5 * (X - x02).^2./sx2.^2 - 0.5 * (Y - y02).^2./sy2.^2 ) ) +  a3*( exp( -0.5 * (X - x03).^2./sx3.^2 - 0.5 * (Y - y03).^2./sy3.^2 ) ) +  a4*( exp( -0.5 * (X - x04).^2./sx4.^2 - 0.5 * (Y - y04).^2./sy4.^2 ) )', 'independent', {'X', 'Y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf 0 0 0 0 0 0 0 0 80 80 80 80 90 140 50 215];
opts.MaxFunEvals = 6000;
opts.MaxIter = 4000;
opts.StartPoint = [0.5 0.4 0.2 0.3 5 5 5 5 5 15 5 5 82 82 82 82 92 145 55 220];
opts.Upper = [Inf Inf Inf Inf 9 9 9 9 15 25 15 15 85 85 85 85 95 150 60 225];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'c vs. x, y', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel y
zlabel c
grid on
view( 90.0, 0.0 );


